### PR TITLE
Fixed #41: added suggestOptions property to mlSearch service, with adhoc override

### LINKED ISSUE #41: Different options for suggest
We were struck by an issue that if you use no-results, /v1/suggest doesn't return suggestions either. We then wanted to override search options for /v1/suggest, but had to use monkey patching to get this working. A suggestOptions option on factory.newContext would make this easier.

```javascript
 var mlSearch = searchFactory.newContext({queryOptions:'no-results'});
          
      // Monkey patch mlSearch, to fix suggest
      mlSearch._suggest = mlSearch.suggest;
      mlSearch.suggest = function(qtext) {
        var _options = mlSearch.options.queryOptions;
        mlSearch.options.queryOptions = 'all';
        var result = mlSearch._suggest(qtext);
        mlSearch.options.queryOptions = _options;
        return result;
      };
```

### PR DESCRIPTION
**Pull request by grtjn**
Fixes #41

### CODE REVIEW

**Comment by joemfb** [comment]
Sorry for the delay in giving feedback. This PR will obviously need a rebase.

Some thoughts:

- I'd like to avoid having `setQueryOptions()` and `setSuggestOptions()` at this time. I think the option to switch those should have some lifecycle hooks around it (may need to re-request storedOptions, re-run search, etc.), so I don't think a simple setter is sufficient.
- I'd like `defaults.suggestOptions` to be `null` instead of `undefined`, for continuity with the other defaults.
- Can the options param to both `MLSearchController.prototype.suggest` and `MLSearchContext.suggest` be a string? Is there any advantage to it being an option with one of two properties?

Also, can you add some test cases?

**Comment by grtjn** [comment]
- Getting rid of the setters.
- I'll fix the undefined
- Options instead of string: options object seemed common to me in ml-search, see search() and values() for instance. It allows easy extension, without having to deal with clumsy optional extra params and such. 
- Test cases, I was afraid you were going to ask that.. :p

**Comment by grtjn** [comment]
better?

**Comment by joemfb** [comment]
Yeah, this is good. I like the idea of extending `suggest()` to take custom options for a combined query, instead of just allowing separate stored options. What if we made the `suggest()` implementation more like the `values()` implementation in that regard:

    params.options = _.isString(options) ? options : this.suggestOptions || this.queryOptions;

Then, in the callback to `getCombinedQuery()`:

    if ( _.isObject(options ) {
      combined.search.options = options;
    }

So the `options` parameter to `MLSearchContext.suggest()` (and `MLSearchController.suggest()`) would be optional, and could be a string or an object.

Thoughts?

**Comment by grtjn** [comment]
Makes sense. I'll see what I can do..

**Comment by grtjn** [comment]
Ok, that should leave test-cases as last thing to do..

**Comment by grtjn** [comment]
Ok, done..

**Comment by joemfb** [comment]
Thanks, it looks good!

I do see one problem, and that relates to the `options` argument supporting three states: string, object with options name, or object for combined query. The middle state will also be passed as a combined query, which isn't what we want ...

Is there any ongoing value in supporting the `options.suggestOptions` or `options.queryOptions`? It seems to me like two cases is sufficient: either pass the stored-options name as a string, or pass the the options you want for a combined query.

Also, can you update the JSDoc for both controller and service `suggest()` methods? You can list multiple types: `@param {Object|String} [options] - ...`

Thoughts?

**Comment by grtjn** [comment]
Ah, point taken. No need to pass options name within options when passing in adhoc query..

**Comment by grtjn** [comment]
That should do it! :-P

**Comment by joemfb** [comment]
thanks!

**Pull request merged**
