### PR TITLE
Add showMoreFacets

### PR DESCRIPTION
**Pull request by patrickmcelwee**
We are using this on dmlc-hc2

Joe, I tested this by running it locally with dmlc-hc2 ... but let me know if you prefer that I write some tests. Would be happy to do it. Happy to hear any suggestions for improvement too (my first time working with angular).

Also, should I check in the dist directory? I notice that it's checked in, but I figured you probably only updated when cutting a new version.

### CODE REVIEW

**Comment by joemfb** [comment]
Hey Patrick, thanks for putting this together!

You're exactly right about `dist/`; I'd lack to limit that to release commits.

Two requests:

- Would you go ahead and add the unit tests? The is functionality is a bit complicated, and could be a candidate for regressions down the line.
- Also, could you add support for showing more facets to the built-in facet templates (`ml-facets.html` and `ml-facets-inline.html`)?

Let me know if I can help.

**Comment by patrickmcelwee** [comment]
OK ... added some tests. There is some additional possible configuration that could be added (like configuring how many additional facets should be returned ... now hard-coded to return 5), but left it simple for our existing use case for now.

I also added to the facet templates, based on the way we are doing it in dmlc-hc. You might take a look and make sure it looks sane, since I didn't directly test it.

**Comment by joemfb** [comment]
One more request before I merge: would you rebase and squash your commits down to 1? (`git rebase -i HEAD~3`, then change the last two from "pick" to "squash").

Thanks, this looks great!

**Comment by patrickmcelwee** [comment]
yep, no problem! ... squashed it down

**Pull request merged**
