### PR TITLE
refactors `value()` implementation

### LINKED ISSUE #59: Make values a little smarter
Make it check storedOptions for presence of values config with given name. If missing, look for facet config with that name.

For fun, also accept an array of (facet) names, to dynamically construct a tuples config based on multiple facet configs..

### PR DESCRIPTION
**Pull request by joemfb**
and simplifies `showMoreFacets()` / `getAggregates()`

based on #61 
closes #59 #61

### CODE REVIEW

**Comment by joemfb** [comment]
I tried further abstracting `showMoreFacets()` / `getAggregates()` by creating something like `getValuesFromConstraint()`, but `getAggregates()` has special requirements of modifying the values definition before making the request.

If we come across other such requirements, it'd be easy to add a method like that. In the meantime, the building blocks are simpler and cleaner.

Thoughts?

/cc @grtjn

**Comment by grtjn** [comment]
Looks very clean, good work!

I think you are right about the three flavors of using values: getting more facet values, getting aggregates, and just getting values. You kind of eliminated the functionality to allow calling values() with a facetName, but that is pretty much covered by the showMoreFacets function anyhow.

Just thinking if that showMore function could be generalized a little. The name sounds rather specific, though the code is pretty close to values accepting a facetName. The most important diff I think would be the extra start option, but you don't need that since you can derive that from the facetValues count..

Something that would really add something new would be allowing getting tuples for facets. E.g. calling a tuples function that takes facetNames, and generates a tuples config for that on the fly. But that could be a separate PR..

**Comment by joemfb** [comment]
I've added a `valuesFromConstraint()` method, and refactored `showMoreFacets()`. Can figure out how to make `getAggregates()` take advantage though, since it has to manipulate the values definition prior to the request.

Thoughts?

**Comment by grtjn** [comment]
The only thing I can think of is to split getAggregates to isolate the part that builds the options with aggregates, and makes the call for one facet. You could call that one aggregatesFromConstraint perhaps, and rename getAggregates to something better as well.

Otherwise very nice and clean. I can see a tuples and a tuplesFromConstraint appearing in future..

**Comment by joemfb** [comment]
I think refactoring `getAggregates()` into lower-level pieces could be useful. `values()` should work for tuples as-is, but we might need a `tuplesFromConstraint()`. Lets make those separate PRs.

**Pull request merged**
