### PR TITLE
Negation facet support

### PR DESCRIPTION
**Pull request by hunterwilliams**
#63. This currently is mostly a refactor to support adding negation. Wanted to do this in iterations as discussed.

The biggest issue is this currently fails the test for the AND/OR mode swapping. This is because in OR mode it fails due to not being able to handle a list. 

`` if ( self.options.facetMode === 'or' ) {
            queries.push( constraintFn( facet.values ) );
          } else {
            queries = queries.concat( _.map(facet.values, constraintFn) );
          } ``

Is this there to take advantage of a MarkLogic optimization when building queries or to just make the query shorter? I could add more logic around this point for negation in the future but wasn't sure if it could be wholly removed since they both seem to do the same thing different ways.

### CODE REVIEW

**Comment by hunterwilliams** [comment]
2f7db6c doesn't allow deserialization from a fresh page load
Hopefully as I add more tests I will iron out what I've missed. Also still need to do gui

**Comment by joemfb** [comment]
Can you expand on how deserialization from a fresh page load isn't working? Is there an error, or missing data? I'm having trouble reproducing.

**Comment by hunterwilliams** [comment]
The prefix is getting stripped if you have it in the URL.

Given a slush marklogic project -> http://localhost:3000/search?n=eyeColor:Blue redirects to http://localhost:3000/search

**Comment by joemfb** [comment]
Check out the facet condition in `getCurrentParams()`, you may need to duplicate that for negated facets.

Also, when you get a chance, could you try to rebase this branch onto master?

    git rebase master
    # assuming no errors ...
    # git push origin negation-facet-support -f

I pushed some minor bug fixes, and got the test coverage back to 100%

**Comment by hunterwilliams** [comment]
@joemfb 1578875 gets it working but it also makes a hack to get it to work. Not sure if something upstream should be updated to deal with facet negation or not.. Or it may be something to consider looking into if you rework facets

**Comment by joemfb** [comment]
Hey, thanks for slogging through this; it's been a ton of work. I'm out this week, but I'll definitely have time for an in-depth review early next week (I'll look sooner if I can).

**Comment by joemfb** [comment]
Sorry for the delay, here's my feedback:

I think this looks really good. I've got a couple last minute tweaks to request, and then I think it'll be ready to merge.

**style issues**:

- inconsistent `var` indentation, please make the variable names align (for instance `selectFacet`, getFacetParams`, etc.)
- inconsistent indentation (see the "hack" in `annotateActiveFacets`)
- trailing whitespace

**tests*:

- the coverage report shows the need for some additional tests for the MLSearchController and MLSearchContext additions (see the detailed report in `./coverage/PhantomJS\ 1.9.8\ \(Mac\ OS\ X\ 0.0.0\)/`)

**additions**:

- make facet negation button in `ml-facets.html` optional (create a `scope.shouldNegate` property, similar to `scope.showShowMore`)

**removals**:

- `selectNegatedFacet()` contains duplicate functionality, and is unused
- `toggleNegatedFacet()` seems unnecessary in the API. I think having `MLSearchController.toggleNegatedFacet()` in the controller is sufficient (and that can just invoke `toggleFacet(?, ?, true)`

**questions**:

- do the "inline-style" facets still make sense with negation?
- I don't understand the aforementioned "hack" in `annotateActiveFacets`. Can you comment (here or in the src) as to why that's needed?

Let me know if you have any questions, and thanks again for tackling this.

**Comment by hunterwilliams** [comment]
I had a hard time coming up with a test case for lines 974-976. Other than that and any missed documentation updates I think it's mostly finished

**Comment by joemfb** [comment]
Here's the missing test:

First, rename the test at 1241 (`should populate from facet URL params`) to `should populate from facet URL params without results`.

Then, add this after it:

    it('should populate from facet URL params with results', function() {
      var search = factory.newContext();

      search.results = {facets: {cartoon: {type: 'string', facetVvalues: [
        { value: 'bugs bunny', name: 'bugs bunny', count: 1 }
      ]}}};

      $location.search({ q: 'hi', f: 'cartoon:"bugs bunny"', n: 'cartoon:"donald duck"' });
      search.fromParams();
      $rootScope.$apply();

      expect(search.getText()).toEqual('hi');
      expect(search.getActiveFacets().cartoon.values[0].value).toEqual('bugs bunny');
      expect(search.getActiveFacets().cartoon.values[0].negated).toEqual(false);
      expect(search.getActiveFacets().cartoon.values[1].value).toEqual('donald duck');
      expect(search.getActiveFacets().cartoon.values[1].negated).toEqual(true);

      $location.search({ q: 'hi' });
      search.fromParams();
      $rootScope.$apply();

      expect(search.getText()).toEqual('hi');
      expect(search.getActiveFacets().cartoon).toBeUndefined();
    });

**Pull request merged**
