### PR TITLE
Fixed #30: added duration filter that applies automatic formatting

### LINKED ISSUE #30: Suggestion: expose ml-duration as a filter
Have you considered exposing ml-duration as filter instead of as directive? (Or maybe have directive use filter) Not sure it provides real benefits, but sounds more logical. Bit like date filter, and such..

### PR DESCRIPTION
**Pull request by grtjn**
Fixes #30

### CODE REVIEW

**Comment by joemfb** [comment]
Can you add JSDoc comments describing the filter and how to use it? You could just add to the `ml-duration` comment block, or create a new block above `durationFilter()`:

  /**
   * angular filter; parses ISO duration (`xs:duration`) strings and creates a string description
   *
   * @namespace duration-filter
   */

Also, could you rebase this branch onto master (`git rebase master`)?

**Comment by grtjn** [comment]
Weird, this new style checking is pretty strict. Blank lines above and below angular.extend are not allowed?

```
Illegal trailing whitespace at directives/ml-duration.directive.js :
    46 |        seconds: 'seconds',
    47 |      };
    48 |      
--------------^
    49 |      angular.extend(_options, options);
    50 |      

Illegal trailing whitespace at directives/ml-duration.directive.js :
    48 |      
    49 |      angular.extend(_options, options);
    50 |      
--------------^
    51 |      if (duration.years) {
    52 |        result.push(duration.years + ' ' + (duration.years > 1 ? _options.years : _options.year));
```

**Comment by grtjn** [comment]
Updated with my changes so far. gulp still complains about the style. Why does it complain about empty lines? And is the jsdoc good like this?

**Comment by joemfb** [comment]
The gulp lint-style task is complaining about trailing whitespace, not new lines. You can setup your editor to delete trailing whitespace on save, or just manually cleanup the lines it highlights.

The JSDoc, looks good. Could you update `Parts with 0 are suppressed` to something like `Duration properties that aren't present will be suppressed`?

Than, I'll be ready to merge. Thanks!

**Comment by grtjn** [comment]
trailing whitespace: there is no trailing whitespace. Oooooh, wait. The blank lines likely contain whitespace!

**Comment by grtjn** [comment]
Ok, that should it..

**Comment by joemfb** [comment]
looks good, thanks!

**Pull request merged**
