### PR TITLE
Fixes #99, and closes marklogic/slush-marklogic-node#319

### LINKED ISSUE #99: Angular bootstrap directive changes
As mentioned [here](https://github.com/marklogic/slush-marklogic-node/issues/319) ml-search is currently using typeahead which is now depreciated. I'll put in a PR to change it to uib-typeahead

### PR DESCRIPTION
**Pull request by Audarth**
I only had to change typeahead to uib-typeahead but I also added angular bootstrap to the bower file (not sure if I've done this correctly) and ran gulp to rebuild it

### CODE REVIEW

**Comment by grtjn** [comment]
#99

**Comment by grtjn** [comment]
I expect Joe will ask you to drop the .min.js changes from this PR. He will build and test upon release..

**Comment by joemfb** [comment]
Thanks for pulling this together, @Audarth! I've got a couple requests:

- @grtjn is right; I only touch `dist/` on release commits. Can you rebase this branch and remove `dist/`

- as for the `angular-bootstrap` dependency, it's only required for the `ml-input` templates (and they'd still probably work without it). Other templates use bootstrap classes, but they'll obviously work without it. Because of that, I'd rather not explicitly depend on `angular-bootstrap` (but I'm open to being convinced).

**Comment by grtjn** [comment]
I'd argue that the out of the box ml-input uses angular-bootstrap's typeahead feature, and you can't really configure its use.

Having said that, it does gracefully decay, and simply don't do typeahead if angular-bootstrap is not loaded. And the typeahead is not essential to have a working ml-input. I could go either way with this.

The only other argument for the explicit dependency would be an explicit pointer to which version of angular-bootstrap would be needed to make it work..

**Comment by Audarth** [comment]
Okay, I've removed the changes to `dist`! 

As for having `angular-bootstrap` as a dependency, I don't really have a strong opinion either way so I'll leave that decision up to you guys!

**Comment by joemfb** [comment]
Hi @Audarth, I'd like to remove the explicit `angular-bootstrap` dependency from `bower.json`. I'll open a new ticket to track the issue of better documenting the dependency.

**Comment by Audarth** [comment]
Cool will do, I'll also do a more thorough test tomorrow, I've done a quick check and it returned network responses though my db at the time was a bit sparse so it didn't have anything to suggest!

**Comment by Audarth** [comment]
Removed the bower change and double checked today with my latest slush and got the "Collection:" constraint in the type ahead as @grtjn mentioned so it seems all good!

**Comment by joemfb** [comment]
Awesome!

**Pull request merged**
